### ISSUE TITLE
Method Genius\StorageClear\Console\StorageClear::handle() does not exist

### ISSUE THREAD

**Issue by christiantosta** [estudiogenius/oc-storageclear-plugin#4]
My Environment: 

OctoberCMS build: 431
Plugin Version: 1.1.1

When running:

> [root@aymores october]# php artisan storage:clear
> 
> In BoundMethod.php line 135:
>                                                                             
>   Method Genius\StorageClear\Console\StorageClear::handle() does not exist  
> 
                               

Traceback:

> ReflectionException: Method Genius\StorageClear\Console\StorageClear::handle() does not exist in /usr/local/share/october/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:135
> Stack trace:
> #0 /usr/local/share/october/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(135): ReflectionMethod->__construct(Object(Genius\StorageClear\Console\StorageClear), 'handle')
> #1 /usr/local/share/october/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(115): Illuminate\Container\BoundMethod::getCallReflector(Array)
> #2 /usr/local/share/october/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): Illuminate\Container\BoundMethod::getMethodDependencies(Object(October\Rain\Foundation\Application), Array, Array)
> #3 /usr/local/share/october/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
> #4 /usr/local/share/october/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(October\Rain\Foundation\Application), Array, Object(Closure))
> #5 /usr/local/share/october/vendor/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\Container\BoundMethod::call(Object(October\Rain\Foundation\Application), Array, Array, NULL)
> #6 /usr/local/share/october/vendor/laravel/framework/src/Illuminate/Console/Command.php(180): Illuminate\Container\Container->call(Array)
> #7 /usr/local/share/october/vendor/symfony/console/Command/Command.php(252): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
> #8 /usr/local/share/october/vendor/laravel/framework/src/Illuminate/Console/Command.php(167): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
> #9 /usr/local/share/october/vendor/symfony/console/Application.php(918): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
> #10 /usr/local/share/october/vendor/symfony/console/Application.php(222): Symfony\Component\Console\Application->doRunCommand(Object(Genius\StorageClear\Console\StorageClear), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
> #11 /usr/local/share/october/vendor/symfony/console/Application.php(129): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
> #12 /usr/local/share/october/vendor/laravel/framework/src/Illuminate/Console/Application.php(88): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
> #13 /usr/local/share/october/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(121): Illuminate\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
> #14 /usr/local/share/october/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
> #15 {main}

**Comment by christiantosta** [comment]
Adding this code to StorageClear console classes should fix the issue:

`    public function handle()
    {
        return $this->laravel->call([$this, 'fire']);
    }
`
